Update run-download.py
datatime27/videos pull request #4
Opened 2024-06-19 13:16 UTC by Headedbranch225

2024-06-20 15:26 UTC, datatime27 requested changes

2024-06-20 15:26 UTC, datatime27 commented on word-tracker/run-download.py
> -CAPTIONS_DIR = 'mrbeast'
Let's not use input.
If we want this to be configurable, let's use command line arguments.
That way you can rerun the command line easily if it fails

2024-06-21 10:45 UTC, Headedbranch225 commented
when I tried to use command line args, it didn't seem to be in the right format and made an error that I didn't want to solve, but I think it would be better to do CLI than having to edit the file for the inputs

2024-07-23 00:20 UTC, scratchusernamemrtbts commented
> when I tried to use command line args, it didn't seem to be in the right format and made an error that I didn't want to solve, but I think it would be better to do CLI than having to edit the file for the inputs

what error showed up?
i might be able to solve it

2025-10-20 18:42 UTC, closed without merging